name: Bug Report
description: File a bug report.
labels: "bug"
assignees: "gigagrug"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug! If you need real-time help, join us on Discord.
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      placeholder: |
        1. ...
        2. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - Windows
        - Linux
        - Mac
    validations:
      required: true
  - type: dropdown
    id: arch
    attributes:
      label: ARCH
      options:
        - amd64
        - arm64
    validations:
      required: true
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Made sure you're on the latest version.
          required: true
        - label: Read the docs.
          required: true
        - label: Check that there isn't already an issue that reports the same bug.
          required: true
